version: '3.8'

# Standalone docker-compose for running just the Leash Gateway services
# The demo app runs separately as a Next.js application

services:
  # Envoy Proxy - Main gateway entry point
  envoy:
    image: envoyproxy/envoy:v1.28-latest
    ports:
      - "8080:8080"  # Gateway port for LLM traffic
      - "9901:9901"  # Admin interface
    volumes:
      - ../configs/envoy/bootstrap-simple.yaml:/etc/envoy/bootstrap.yaml:ro
    depends_on:
      - module-host
    environment:
      - ENVOY_LOG_LEVEL=info
    command: ["/usr/local/bin/envoy", "-c", "/etc/envoy/bootstrap.yaml", "--service-cluster", "leash-gateway"]
    networks:
      - leash-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9901/ready"]
      interval: 10s
      timeout: 5s
      retries: 3

  # Module Host - Processes requests through security modules
  module-host:
    build:
      context: ..
      dockerfile: docker/Dockerfile.module-host
    ports:
      - "50051:50051"  # gRPC port for ext_proc
      - "8081:8081"    # Health check endpoint
      - "9090:9090"    # Prometheus metrics
    environment:
      - DATABASE_URL=postgres://leash:leash@postgres:5432/leash?sslmode=disable
      - REDIS_URL=redis://redis:6379
      - LOG_LEVEL=info
      - CONFIG_PATH=/etc/leash/config.yaml
      # API Keys - Set these via environment or .env file
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    volumes:
      - ../configs/gateway:/etc/leash:ro
    networks:
      - leash-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8081/health"]
      interval: 10s
      timeout: 5s
      retries: 3

  # PostgreSQL - Stores configuration and usage data
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: leash
      POSTGRES_USER: leash
      POSTGRES_PASSWORD: leash
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ../scripts/init-db.sql:/docker-entrypoint-initdb.d/init.sql:ro
    ports:
      - "5433:5432"  # Exposed on 5433 to avoid conflicts
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U leash"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - leash-network

  # Redis - Caching and rate limiting
  redis:
    image: redis:7-alpine
    ports:
      - "6380:6379"  # Exposed on 6380 to avoid conflicts
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3
    networks:
      - leash-network

  # Prometheus - Metrics collection
  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9091:9090"  # Exposed on 9091 to avoid conflicts
    volumes:
      - ../configs/prometheus:/etc/prometheus:ro
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.enable-lifecycle'
    networks:
      - leash-network

  # Grafana - Metrics visualization (optional)
  grafana:
    image: grafana/grafana:latest
    ports:
      - "3002:3000"  # Exposed on 3002 to avoid conflicts with demo app
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_INSTALL_PLUGINS=redis-datasource
    volumes:
      - grafana_data:/var/lib/grafana
    networks:
      - leash-network
    profiles:
      - monitoring  # Only start if --profile monitoring is specified

volumes:
  postgres_data:
  redis_data:
  prometheus_data:
  grafana_data:

networks:
  leash-network:
    driver: bridge
